### PR TITLE
README page to the demo

### PR DESCRIPTION
**Pull request by ayan-joshi**
## References

It solves the issue #63 , I have added the Readme file with proper explanation from the slides and the youtube video

## Submitter checklist

- [x] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] Recommended: If you participate in Hacktoberfest 2023, make sure you're [signed up](https://wiremock.org/events/hacktoberfest/) there and in the WireMock form 
- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

Have a look at my pr @oleg-nenashev

### CODE REVIEW

**Comment by dirkbolte-otto** [comment]
Thanks for the PR. @oleg-nenashev suggested in the original issue to include some links + a description on how to start the demo. Can you provide this as well?

**Comment by dirkbolte** [comment]
Thanks for the PR. @oleg-nenashev suggested in the original issue to include some links + a description on how to start the demo. Can you provide this as well?

**Comment by ayan-joshi** [comment]
@dirkbolte did the remaining changes have a look sir

**Review by dirkbolte — APPROVED** [review]

**Comment by ayan-joshi** [comment]
@dirkbolte Thanks , Can you provide the hacktoberfest label to it

**Pull request merged**
